In [1]:
import numpy as np


# Getting Started with NumPy

In [2]:
data = np.load('monthdata.npz')
totals = data['totals']
counts = data['counts']

In [3]:
#summing all rows (percip for each city) producing array
rowTotals = np.sum(totals, axis=1)

In [4]:
#finding index of where the lowest percip is
minIndex = np.where(rowTotals == np.amin(rowTotals))

## City with lowest total precipitation:

In [5]:
minIndex[0][0]

8

In [6]:
#summing along columns to find total percip per month
totPercipMonth = np.sum(totals, axis=0)

In [7]:
#summing along columns to find total cities per month
totalCountMonth = np.sum(counts, axis=0)

In [8]:
#finding averge percip per month
avgPercipMonth = np.divide(totPercipMonth, totalCountMonth)


##  Average precipitation in each month:

In [9]:
avgPercipMonth

array([27.77978339, 30.42629482, 29.41007194, 17.96654275, 21.34456929,
       20.69498069, 24.97718631, 19.85661765, 24.06563707, 44.68441065,
       34.61568627, 32.36679537])

In [10]:
#finding total percip per city by summing along rows
totPercipCity = np.sum(totals, axis=1)

In [11]:
#finding total opservations per city
totalCountCity = np.sum(counts, axis=1)

In [12]:
#finding average percipitation per city
avgPercipCity = np.divide(totPercipCity, totalCountCity)

##  Average precipitation in each City:

In [13]:
avgPercipCity

array([47.77859779, 14.33333333, 39.91232877, 41.44505495, 23.4099723 ,
       23.68144044, 17.52197802, 36.52222222,  6.15426997])

In [14]:
#reshaping 12 months to where every inner array is one quarter
reshaped = totals.reshape(4*len(totals),3)

In [15]:
#summing each quarter for each city. Every element now represent
#one quarter
summedQuarter = np.sum(reshaped, axis= 1)

## Quarterly precipitation totals:

In [17]:
#Reshaping so that each inner array is one cities full year
finalReshape = summedQuarter.reshape(len(totals), 4)
finalReshape

array([[5450, 1408, 1466, 4624],
       [ 189, 1339, 3148,  527],
       [3120, 3357, 3386, 4705],
       [4416, 3321, 2024, 5325],
       [2024, 1498, 1721, 3208],
       [1786, 1809, 2557, 2397],
       [1583, 1296, 1729, 1770],
       [4602, 1340, 1250, 5956],
       [ 338,  524,  922,  450]], dtype=uint64)